### ISSUE TITLE
Nested Dictionaries Cause Syntax Error

### ISSUE THREAD

**Issue by Alternus** [nekitdev/braces.py#3]
Just found this module and love it, however I've noticed that using nested dictionaries will causes a Syntax Error.
For example:
```python
# coding: braces
test = {"layer1": {"layer2": "test"}}
```
Will result in:
```
SyntaxError: encoding problem: braces
```

**Comment by nekitdev** [comment]
Thanks for your feedback! Glad you enjoy playing around with the library.
I haven't really touched it in a while, but it's interesting that nested dictionaries cause SyntaxError.
I'll look into that later; all in all, I feel it's better to rewrite the project overall.

**Comment by Alternus** [comment]
Awesome, it's a great concept (especially after transitioning back to Python from other languages). I'd offer to help but this kind of Python programming is a bit out of my area, happy to assist debugging a newer version if/when you ever decide to rewrite the project though!

**Comment by nekitdev** [comment]
Unfortunately, I did not really have time to work on this project. Although, this issue is being closed by https://github.com/nekitdev/braces.py/commit/4affc43043d4b1a30e456ae03e28c3e05090c2fe and https://github.com/nekitdev/braces.py/commit/7bbd0ca58a344789ae661b7cdc1f1d3d5e1f267c.
